"""
app/cli.py
CLI entry point for pip-installed usage.

After pip install ai-repo-manager:
    ai-repo-manager start           → start server
    ai-repo-manager setup           → interactive setup wizard
    ai-repo-manager test-webhook    → test GitHub webhook connection
    ai-repo-manager health          → check all components
    ai-repo-manager version         → show version info

Short alias:
    arm start
    arm setup
    arm health
"""

import argparse
import os
import sys


def cmd_start(args):
    """Start the AI Repo Manager server."""
    workers = getattr(args, "workers", 1)
    port    = getattr(args, "port", 5000)
    timeout = getattr(args, "timeout", 120)

    _check_required_env()

    print(f"""
╔══════════════════════════════════════════╗
║      GitHub Autopilot — Starting       ║
╚══════════════════════════════════════════╝

→ Workers:  {workers}
→ Port:     {port}
→ Timeout:  {timeout}s
→ Env:      {'✅ All required vars set' if _check_required_env(silent=True) else '⚠️  Some vars missing'}

Starting gunicorn...
""")

    os.execvp("gunicorn", [
        "gunicorn",
        "server:app",
        f"--workers={workers}",
        f"--timeout={timeout}",
        f"--bind=0.0.0.0:{port}",
        "--worker-class=gthread",
        "--threads=8",
    ])


def cmd_setup(args):
    """Interactive setup wizard."""
    print("""
╔══════════════════════════════════════════╗
║    GitHub Autopilot — Setup Wizard     ║
╚══════════════════════════════════════════╝

This wizard will help you configure the bot.
""")

    env_vars = {}

    print("📋 Step 1 — GitHub App Credentials\n")
    env_vars["GITHUB_APP_ID"]          = input("  GitHub App ID (numeric): ").strip()
    env_vars["GITHUB_WEBHOOK_SECRET"]  = input("  Webhook Secret: ").strip()
    print("  Private key: Paste the content of your .pem file")
    print("  (Press Ctrl+D / Ctrl+Z when done)")
    lines = []
    try:
        while True:
            lines.append(input())
    except EOFError:
        pass
    env_vars["GITHUB_PRIVATE_KEY"] = "\n".join(lines)

    print("\n🤖 Step 2 — LLM API Keys\n")
    env_vars["GROQ_API_KEY"]    = input("  Groq API Key (required, free at console.groq.com): ").strip()
    gemini                      = input("  Gemini API Key (optional, free at aistudio.google.com): ").strip()
    openrouter                  = input("  OpenRouter API Key (optional, free at openrouter.ai): ").strip()
    if gemini:
        env_vars["GEMINI_API_KEY"] = gemini
    if openrouter:
        env_vars["OPENROUTER_API_KEY"] = openrouter

    print("\n💾 Step 3 — Redis\n")
    redis = input("  Redis URL (default: redis://localhost:6379/0): ").strip()
    env_vars["REDIS_URL"] = redis or "redis://localhost:6379/0"

    print("\n🔔 Step 4 — Notifications (optional)\n")
    discord = input("  Discord Webhook URL (skip with Enter): ").strip()
    slack   = input("  Slack Webhook URL (skip with Enter): ").strip()
    if discord:
        env_vars["DISCORD_WEBHOOK_URL"] = discord
    if slack:
        env_vars["SLACK_WEBHOOK_URL"] = slack

    # Write .env file
    env_content = "\n".join(f'{k}="{v}"' for k, v in env_vars.items() if v)
    with open(".env", "w") as f:
        f.write(f"# GitHub Autopilot — Generated by `autopilot setup`\n{env_content}\n")

    print("""
✅ Configuration saved to .env

Next steps:
  1. Run: arm start
  2. Install GitHub App: github.com/settings/apps
  3. Set Webhook URL to your server URL + /webhook
  4. Install app on your repositories

📖 Full guide: https://github.com/Shweta-Mishra-ai/github-autopilot#readme
""")


def cmd_health(args):
    """Check all components."""
    print("""
╔══════════════════════════════════════════╗
║      GitHub Autopilot — Health            ║
╚══════════════════════════════════════════╝
""")

    checks = []

    # Env vars
    required = ["GITHUB_APP_ID", "GITHUB_PRIVATE_KEY", "GITHUB_WEBHOOK_SECRET", "GROQ_API_KEY"]
    for var in required:
        val   = os.environ.get(var, "")
        icon  = "✅" if val else "❌"
        label = f"{var[:30]:<30}"
        checks.append(f"  {icon} {label} {'SET' if val else 'MISSING'}")

    optional = ["GEMINI_API_KEY", "REDIS_URL", "DISCORD_WEBHOOK_URL", "QDRANT_URL"]
    for var in optional:
        val  = os.environ.get(var, "")
        icon = "✅" if val else "⚠️ "
        checks.append(f"  {icon} {var[:30]:<30} {'SET' if val else 'not set (optional)'}")

    print("Environment Variables:")
    print("\n".join(checks))

    # Redis
    print("\nRedis:")
    try:
        import redis as redis_lib
        r   = redis_lib.from_url(os.environ.get("REDIS_URL", "redis://localhost:6379/0"))
        r.ping()
        print("  ✅ Redis connected")
    except Exception as e:
        print(f"  ❌ Redis unavailable: {e}")

    # LLM providers
    print("\nLLM Providers:")
    groq_key = os.environ.get("GROQ_API_KEY", "")
    print(f"  {'✅' if groq_key else '❌'} Groq          {'configured' if groq_key else 'GROQ_API_KEY missing'}")
    gem_key = os.environ.get("GEMINI_API_KEY", "")
    print(f"  {'✅' if gem_key else '⚠️ '} Gemini Flash  {'configured' if gem_key else 'not set (optional)'}")
    or_key = os.environ.get("OPENROUTER_API_KEY", "")
    print(f"  {'✅' if or_key else '⚠️ '} OpenRouter    {'configured' if or_key else 'not set (optional)'}")

    print()


def cmd_version(args):
    """Show version info."""
    from app import __version__
    print(f"""
AI Repo Manager v{__version__}

GitHub:  https://github.com/Shweta-Mishra-ai/github-autopilot
Author:  Shweta Mishra
License: MIT

Commands: ai-repo-manager --help
Alias:    arm --help
""")


def cmd_test_webhook(args):
    """Test webhook connection."""
    server_url = args.url or os.environ.get("SERVER_URL", "http://localhost:5000")
    print(f"\nTesting webhook at {server_url}/health ...")
    try:
        import requests
        r = requests.get(f"{server_url}/health", timeout=10)
        if r.status_code == 200:
            data = r.json()
            print("  ✅ Server online")
            print(f"  Status: {data.get('status', 'unknown')}")
            print(f"  Version: {data.get('version', 'unknown')}")
            providers = data.get("checks", {}).get("llm_providers", {})
            for pk, ps in providers.items():
                state = ps.get("state", "unknown")
                icon  = "✅" if state == "closed" else "⚠️"
                print(f"  {icon} {pk}: {state}")
        else:
            print(f"  ❌ Server returned HTTP {r.status_code}")
    except Exception as e:
        print(f"  ❌ Cannot connect: {e}")
        print(f"  Is the server running at {server_url}?")
    print()


def _check_required_env(silent: bool = False) -> bool:
    required = [
        "GITHUB_APP_ID",
        "GITHUB_PRIVATE_KEY",
        "GITHUB_WEBHOOK_SECRET",
        "GROQ_API_KEY",
    ]
    missing = [v for v in required if not os.environ.get(v)]
    if missing and not silent:
        print(f"❌ Missing required environment variables: {', '.join(missing)}")
        print("   Run: arm setup  (to configure interactively)")
        print("   Or:  set them in .env file")
        sys.exit(1)
    return not missing


def main():
    parser = argparse.ArgumentParser(
        prog="ai-repo-manager",
        description="GitHub Autopilot — AI-powered GitHub automation",
    )
    parser.add_argument("--version", action="version", version="4.0.0")

    sub = parser.add_subparsers(dest="command", metavar="COMMAND")
    sub.required = True

    # start
    p_start = sub.add_parser("start", help="Start the server")
    p_start.add_argument("--port",    type=int, default=5000,  help="Port (default: 5000)")
    p_start.add_argument("--workers", type=int, default=1, help="Gunicorn workers (default: 1)")
    p_start.add_argument("--timeout", type=int, default=120,   help="Request timeout (default: 120)")
    p_start.set_defaults(func=cmd_start)

    # setup
    p_setup = sub.add_parser("setup", help="Interactive setup wizard")
    p_setup.set_defaults(func=cmd_setup)

    # health
    p_health = sub.add_parser("health", help="Check all components")
    p_health.set_defaults(func=cmd_health)

    # version
    p_ver = sub.add_parser("version", help="Show version")
    p_ver.set_defaults(func=cmd_version)

    # test-webhook
    p_test = sub.add_parser("test-webhook", help="Test server connection")
    p_test.add_argument("--url", default="", help="Server URL (default: $SERVER_URL or localhost:5000)")
    p_test.set_defaults(func=cmd_test_webhook)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
